# The image is built on top of one that has node preinstalled
FROM node:16
# Create app directory
WORKDIR /usr/src/app
# Copy all files into the container
COPY . .
# Install dependencies
RUN npm install
# Open appropriate port 
EXPOSE 5000 5001
# Generate the authentication keys
# RUN npm run generate:key
# Start the application
CMD ["npm", "start"]
